BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `movements` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`time`	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`elevator`	TEXT NOT NULL,
	`origin`	INTEGER NOT NULL DEFAULT 0,
	`destination`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `state_changes` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`time`	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`elevator`	TEXT NOT NULL,
	`stopped_at` INTEGER NOT NULL,
	`accum_moves`	INTEGER NOT NULL DEFAULT 0,
	`last_move`	INTEGER NOT NULL DEFAULT 0
);
COMMIT;
